# This workflow builds and pushes Docker images to Docker Hub when a push is made to the main branch.
#
# Before using this workflow, you need to configure the following secrets in your GitHub repository settings:
# - DOCKERHUB_USERNAME: Your Docker Hub username.
# - DOCKERHUB_TOKEN: A Docker Hub access token with write permissions.
#
# The workflow will build and push images for the 'backend', 'frontend', and 'nginx' services.
# The images will be tagged as:
# - <your-dockerhub-username>/notes-app-backend:latest
# - <your-dockerhub-username>/notes-app-frontend:latest
# - <your-dockerhub-username>/notes-app-nginx:latest

name: Docker Image CI

on:
  push:
    branches: [ "main" ]

jobs:
  build_and_push:
    name: Build and Push Docker Image for ${{ matrix.service }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service: ['backend', 'frontend', 'nginx', 'mysql']

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./${{ matrix.service }}
          file: ./${{ matrix.service }}/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/notes-app-${{ matrix.service }}:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max
